### ISSUE TITLE
Error when running firebase-cloning-tool

### ISSUE THREAD

**Issue by sarfarazmadhia** [epool/firebase-cloning-tool#4]
Traceback (most recent call last):
	20: from /Users/Safy/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
	19: from /Users/Safy/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
	18: from /Users/Safy/.rvm/gems/ruby-2.7.1/bin/firebase-cloning-tool:23:in `<main>'
	17: from /Users/Safy/.rvm/gems/ruby-2.7.1/bin/firebase-cloning-tool:23:in `load'
	16: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/firebase-cloning-tool-0.1.6/bin/firebase-cloning-tool:3:in `<top (required)>'
	15: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/firebase-cloning-tool-0.1.6/bin/firebase-cloning-tool:3:in `require'
	14: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/firebase-cloning-tool-0.1.6/lib/firebase/cloning/tool.rb:4:in `<top (required)>'
	13: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/firebase-cloning-tool-0.1.6/lib/firebase/cloning/tool.rb:4:in `require'
	12: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-0.13.1/lib/pry.rb:78:in `<top (required)>'
	11: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-0.13.1/lib/pry.rb:78:in `require'
	10: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-0.13.1/lib/pry/cli.rb:134:in `<top (required)>'
	 9: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-0.13.1/lib/pry/cli.rb:40:in `add_plugin_options'
	 8: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-0.13.1/lib/pry/cli.rb:40:in `each'
	 7: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-0.13.1/lib/pry/plugins.rb:55:in `load_cli_options'
	 6: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-0.13.1/lib/pry/plugins.rb:55:in `require'
	 5: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-byebug-3.6.0/lib/pry-byebug/cli.rb:3:in `<top (required)>'
	 4: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-byebug-3.6.0/lib/pry-byebug/cli.rb:3:in `require'
	 3: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-byebug-3.6.0/lib/pry-byebug/commands.rb:10:in `<top (required)>'
	 2: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-byebug-3.6.0/lib/pry-byebug/commands.rb:10:in `require'
	 1: from /Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-byebug-3.6.0/lib/pry-byebug/commands/exit_all.rb:1:in `<top (required)>'
/Users/Safy/.rvm/gems/ruby-2.7.1/gems/pry-byebug-3.6.0/lib/pry-byebug/commands/exit_all.rb:5:in `<module:PryByebug>': uninitialized constant Pry::Command::ExitAll (NameError)

**Comment by epool** [comment]
this gem is no longer been maintained, since it depends on the firebase console DOM in order to find the buttons and fields it's recommended to use it as a reference and adjust the ids accordingly.
